name: mother_international_comp_website
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.6
  firebase_core: ^1.21.1
  firebase_storage: ^10.3.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^3.0.1
  url_launcher: ^6.1.5
  websafe_svg: ^2.1.2+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/models/
    - assets/images/international winners/
